// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{namespace}/deployments/{pod_name}": {
            "put": {
                "description": "Scale Deployment",
                "tags": [
                    "Deployments"
                ],
                "summary": "Scale Deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of Deployment",
                        "name": "deployment_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Amount of Replicas",
                        "name": "replicas",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/{namespace}/pods/{pod_name}": {
            "delete": {
                "description": "restart pod",
                "tags": [
                    "Pods"
                ],
                "summary": "Restart Pod",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of pod",
                        "name": "pod_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger Backend API",
	Description:      "Backend Server for Competitions",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
