basePath: /api
definitions:
  views.Container:
    properties:
      cpuLimits:
        type: integer
      cpuUsage:
        type: integer
      memoryLimits:
        type: integer
      memoryUsage:
        type: integer
      name:
        type: string
      state:
        type: string
    type: object
  views.Deployment:
    properties:
      name:
        type: string
      replicas:
        type: integer
    type: object
  views.DeploymentPod:
    properties:
      name:
        type: string
      status:
        type: string
    type: object
  views.DeploymentPods:
    properties:
      pods:
        items:
          $ref: '#/definitions/views.DeploymentPod'
        type: array
    type: object
  views.Pod:
    properties:
      age:
        type: string
      containers:
        items:
          $ref: '#/definitions/views.Container'
        type: array
      name:
        type: string
      restarts:
        type: integer
      status:
        type: string
    type: object
host: 127.0.0.1:30000
info:
  contact: {}
  description: Backend Server for Competitions
  termsOfService: http://swagger.io/terms/
  title: Swagger Backend API
  version: "1.0"
paths:
  /kubernetes/{namespace}/deployments/{deployment_name}:
    get:
      description: Get Deployment Information by name and namespace
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - description: Deployment name
        in: path
        name: deployment_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.Deployment'
      summary: Get Deployment Information
      tags:
      - Deployments
    put:
      description: Scale Deployment
      parameters:
      - description: Name of namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: Name of Deployment
        in: path
        name: deployment_name
        required: true
        type: string
      - description: Amount of Replicas
        in: query
        name: replicas
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Scale Deployment
      tags:
      - Deployments
  /kubernetes/{namespace}/deployments/{deployment_name}/describe:
    get:
      description: Describe Deployment
      parameters:
      - description: Name of namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: Name of Deployment
        in: path
        name: deployment_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Describe Deployment
      tags:
      - Deployments
  /kubernetes/{namespace}/deployments/{deployment_name}/rollback:
    post:
      description: Rollback a deployment to the previous version
      parameters:
      - description: Namespace name
        in: path
        name: namespace
        required: true
        type: string
      - description: Deployment name
        in: path
        name: deployment_name
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Rollback Deployment
      tags:
      - Deployments
  /kubernetes/{namespace}/pods:
    get:
      description: Lists Pods by Deployment
      parameters:
      - description: Name of namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: Name of deployment
        in: query
        name: deployment
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.DeploymentPods'
      summary: Lists Pods by Deployment
      tags:
      - Pods
  /kubernetes/{namespace}/pods/{pod_name}:
    delete:
      description: restart pod
      parameters:
      - description: Name of namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: Name of pod
        in: path
        name: pod_name
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Restart Pod
      tags:
      - Pods
    get:
      description: Get Pod Information
      parameters:
      - description: Name of namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: Name of pod
        in: path
        name: pod_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.Pod'
      summary: Get Pod Information
      tags:
      - Pods
  /kubernetes/{namespace}/pods/{pod_name}/describe:
    get:
      description: Describe Pod
      parameters:
      - description: Name of namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: Name of pod
        in: path
        name: pod_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Describe Pod
      tags:
      - Pods
  /kubernetes/{namespace}/pods/{pod_name}/logs:
    get:
      description: Get Pod Logs
      parameters:
      - description: Name of namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: Name of pod
        in: path
        name: pod_name
        required: true
        type: string
      - description: Name of container
        in: query
        name: container
        required: true
        type: string
      - description: Number of lines to show
        in: query
        name: tail
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Pod Logs
      tags:
      - Pods
swagger: "2.0"
